### ISSUE TITLE
REMOVE THIS - what does this mean

### ISSUE THREAD

**Issue by dougaitken** [PebbleSeizureDetect/PebbleSeizureDetect#3]
Been trying to figure out what exactly is the point in this part? 

Aside from that, I'd love to help contribute slightly and have a wee re-write of the readme, remove the license as you have a license file. I'll open a PR with some suggestions later

**Comment by shylesh107** [comment]
I was wondering the same thing.

**Comment by dougaitken** [comment]
So form what I can see it literally means deleting that line or the app won't run. I don't know if @PebbleSeizureDetect means delete line 15, or delete [lines 1 - 15](https://github.com/PebbleSeizureDetect/PebbleSeizureDetect/blob/f7e68491de88ed29571ce47805e528dc21d2cfb6/main.c#L1-L15).

**Comment by shylesh107** [comment]
Looking at the documentation the author means to only delete that single line.

```
In the "main.c" source code file, find the text "[REMOVE THIS]" and delete it
```

I was just curious as to why is it inside the source code in the first place.

**Comment by TeMPOraL** [comment]
I guess it's there to make sure people read the README before installing.

**Comment by PebbleSeizureDetect** [comment]
It means that you should delete only that line, yes.

I added that because I am not 100% sure how various regulatory bodies will treat this type of app.  It has not undergone any clinical trials of course, so offering it as "medical software" could potentially be against the rules.  So I use the "[REMOVE THIS]" line to ensure that the app can't even compile unless the user edits the source code.  This way, it is not functional software at all, without user modification.  Just one extra layer of protection against regulations, I figure :)

**Comment by jones139** [comment]
Thanks for the clarification.  I hadn't thought of that.   I tried to get
round the issue by calling my openseizuredetector pebble app
"experimental"....but you have got me wondering if I need a better
disclaimer now!

from my Phone (hence dodgy spelling!)

**Comment by dougaitken** [comment]
I think if this is the only place you can obtain the app code then you can cover yourself by detailing those concerns in the readme.md. I think if you call this a lifestyle app, and including the no liability in the readme.md, basically saying "if you chose to install this, I'm not responsible for when/if the app doesn't work as you might expect.

**Comment by PebbleSeizureDetect** [comment]
Yes, I tried to add disclaimers to the readme as well, but I figured that additional measures couldn't hurt.  How can you say that this is a "medical device" if it is just a bunch of text, and on top of that, it's text that won't even compile without modification?  But who knows if this is sufficient or needed or what.  I am not a lawyer :)

**Comment by dougaitken** [comment]
Anyone who goes to the effort of sideloading a Pebble app onto their watch and setting up the Twilio account, will understand this is not a medial app but just something you'd released to help out. 

Bottom line, it's released with GPL v3.0 and you've not said it's a medical app, so afaik you're covered.

**Comment by PebbleSeizureDetect** [comment]
Agreed, I doubt any user will ever complain.  But that doesn't mean the FDA would feel the same :)

**Comment by iamajeannie** [comment]
I CAN'T SET THIS UP! SOMEONE HELP ME!
