### ISSUE TITLE
Suggestion: Pebble Time version (aka SDK 3)

### ISSUE THREAD

**Issue by ekosz** [PebbleSeizureDetect/PebbleSeizureDetect#9]
Hey there!

Both of my brothers are epileptic and I saw this software and thought it was a great idea. I figured I buy them some Pebble watches and help install this for them. Unfortunately I didn't realize Seizure Detect didn't work with the Pebble Time.

Are there any plans so create a version for Pebble time? If not, would you like some help?

Thanks!
Eric

**Comment by jones139** [comment]
I think it should be possible to compile it for a pebble time.  I have a
similar app (OpenSeizureDetector) that I compiled for pebble time and
pebble round l and a user reported it working on a time ok.  What sort of
error did you get running it on a time?

Graham (Graham @openseizuredetector.org.UK)

from my Phone (hence dodgy spelling!)

**Comment by ekosz** [comment]
Resolved! Thanks for the super fast feedback. Christmas is saved haha.

**Comment by jones139** [comment]
No problem.  Please feed back how it works (both successful detections and
false alarms) as I am interested in finding an optimum detection
algorithm.....

from my Phone (hence dodgy spelling!)
